"use client";

import { useEffect, useRef } from 'react';
import { useToast } from '@/hooks/useToast';

/**
 * Registers the service worker on mount and handles updates.
 */
export function ServiceWorkerRegistration() {
    const { showToast } = useToast();
    const refreshing = useRef(false);

    useEffect(() => {
        // Skip registration in local development as the service worker is only built for production
        if (process.env.NODE_ENV === 'development') {
            console.log('[App] Service worker skipped in development mode');
            return;
        }

        if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
            // Handle page reload after the new service worker takes over
            navigator.serviceWorker.addEventListener('controllerchange', () => {
                if (refreshing.current) return;
                refreshing.current = true;
                window.location.reload();
            });

            // Register the service worker generated by next-pwa
            navigator.serviceWorker
                .register('/sw.js')
                .then((registration) => {
                    console.log('[App] SW registered');

                    // Check for updates periodically
                    registration.addEventListener('updatefound', () => {
                        const newWorker = registration.installing;
                        if (newWorker) {
                            newWorker.addEventListener('statechange', () => {
                                if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                                    // New version available!
                                    showToast('A new update is available. Refreshing...', 'info');
                                    // With skipWaiting: true in next.config.js, it will take over automatically
                                    // and trigger the controllerchange event above.
                                }
                            });
                        }
                    });
                })
                .catch((err) => {
                    console.error('[App] SW registration failed:', err);
                });
        }
    }, [showToast]);

    return null;
}
